"""Project packaging (Phase 8, NFR-09, AC-04/AC-06).

Zips a project's stored artifacts into a standalone archive: source, tests, plus a Dockerfile,
CI workflow, and README (defaults synthesised only when the agents did not produce them). The
output has no GenesisAI runtime dependency. Re-export just re-zips stored artifacts; no agent run.

ponytail: default infra assumes a Python project. Language-aware infra is a refinement when
non-Python targets ship; the DevOps agent's own Dockerfile/CI override the defaults anyway.
"""

import io
import zipfile
from collections.abc import Iterable
from typing import Protocol

DEFAULT_DOCKERFILE = (
    "FROM python:3.11-slim\n"
    "WORKDIR /app\n"
    "COPY . .\n"
    "RUN pip install --no-cache-dir -e . pytest\n"
    'CMD ["python", "-m", "pytest", "-q"]\n'
)

DEFAULT_CI = (
    "name: CI\n"
    "on: [push, pull_request]\n"
    "jobs:\n"
    "  test:\n"
    "    runs-on: ubuntu-latest\n"
    "    steps:\n"
    "      - uses: actions/checkout@v4\n"
    "      - uses: actions/setup-python@v5\n"
    "        with:\n"
    "          python-version: '3.11'\n"
    "      - run: pip install -e . pytest\n"
    "      - run: pytest -q\n"
)


def _default_readme(name: str) -> str:
    return (
        f"# {name}\n\n"
        "Generated by GenesisAI. This project is standalone and carries no GenesisAI "
        "runtime dependency.\n\n"
        "## Run\n\n```\npip install -e . pytest\npytest\n```\n"
    )


class _CodeArtifact(Protocol):
    path: str
    content: str


class _DocArtifact(Protocol):
    type: str
    content: str


def assemble_files(
    project_name: str, code: Iterable[_CodeArtifact], docs: Iterable[_DocArtifact]
) -> dict[str, str]:
    files: dict[str, str] = {}
    for c in code:
        files[c.path] = c.content
    for d in docs:
        name = "README.md" if d.type.lower() == "readme" else f"docs/{d.type}.md"
        files[name] = d.content
    # Fallbacks so an export always contains the AC-06 set, without overriding agent output.
    files.setdefault("Dockerfile", DEFAULT_DOCKERFILE)
    files.setdefault(".github/workflows/ci.yml", DEFAULT_CI)
    files.setdefault("README.md", _default_readme(project_name))
    return files


def build_archive(files: dict[str, str]) -> bytes:
    buffer = io.BytesIO()
    with zipfile.ZipFile(buffer, "w", zipfile.ZIP_DEFLATED) as archive:
        for path, content in sorted(files.items()):
            archive.writestr(path, content)
    return buffer.getvalue()
